# Generated by Django 6.0.5 on 2026-05-17 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_code', models.CharField(max_length=20, unique=True)),
                ('machine_name', models.CharField(max_length=100)),
                ('factory_zone', models.CharField(max_length=50)),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
            options={
                'db_table': 'machines',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.machine')),
            ],
            options={
                'db_table': 'alerts',
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vibration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('energy_consumption', models.DecimalField(decimal_places=2, max_digits=10)),
                ('load_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('recorded_at', models.DateTimeField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.machine')),
            ],
            options={
                'db_table': 'sensor_data',
            },
        ),
    ]
